import type { Condition } from './Product';

export type ThemeMode = 'system' | 'light' | 'dark';

export interface Settings {
  /** Default percentage markup applied to purchase cost for a price suggestion. */
  defaultMarkupPercent: number;
  /** Fixed markup in currency units, added on top of the percentage markup. */
  defaultMarkupFixed: number;
  /** Suggested prices are raised until at least this profit is reached. */
  minProfit: number;
  /** Optional target margin in percent. When > 0 it overrides the markup rules. */
  targetMargin: number;
  /** Round suggestions to a "psychological" price such as 14,99. */
  roundPrices: boolean;

  defaultCondition: Condition;
  defaultLocation: string;
  defaultPostalCode: string;
  defaultShipping: string;
  defaultPickup: boolean;
  /** Boilerplate appended to every generated description. */
  defaultDescription: string;

  autoOptimizeTitle: boolean;
  autoGenerateDescription: boolean;
  autoPrepareImages: boolean;
  /** Max number of images offered for a listing. */
  maxImages: number;

  floatingButton: boolean;
  contextMenu: boolean;
  debugMode: boolean;

  theme: ThemeMode;
  currency: string;
  locale: string;

  /**
   * Entry point used when opening Willhaben's "Anzeige aufgeben" flow. Kept
   * configurable because the marketplace can change its routes; the content
   * script detects the form by its contents, not by this URL.
   */
  willhabenCreateUrl: string;

  defaultPlatform: string;
}

export const DEFAULT_SETTINGS: Settings = {
  defaultMarkupPercent: 30,
  defaultMarkupFixed: 0,
  minProfit: 5,
  targetMargin: 0,
  roundPrices: true,

  defaultCondition: 'NEU',
  defaultLocation: '',
  defaultPostalCode: '',
  defaultShipping: 'Versand möglich',
  defaultPickup: true,
  defaultDescription: '',

  autoOptimizeTitle: true,
  autoGenerateDescription: true,
  autoPrepareImages: true,
  maxImages: 8,

  floatingButton: true,
  contextMenu: true,
  debugMode: false,

  theme: 'system',
  currency: 'EUR',
  locale: 'de-AT',

  willhabenCreateUrl:
    'https://www.willhaben.at/iad/anzeigenaufgabe/marktplatz?adTypeId=67&productId=67',

  defaultPlatform: 'willhaben',
};
